apiVersion: apps/v1
kind: Deployment
metadata:
  name: daily-task-planner
  labels:
    app: daily-task-planner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daily-task-planner
  template:
    metadata:
      labels:
        app: daily-task-planner
    spec:
      containers:
      - name: task-planner-container
        image: renoacden/daily-task-planner:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        
        
